config/routes.rb
Payroll::Application.routes.draw do
resources :employees  
resources :attendances
resources :deducts
resources :sals

   root :to => 'employees#index'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
belongs_to :employee
has_many :sals

  attr_accessible :attend_day, :cl, :el, :lop, :od, :sl, :wday, :employee_id, :sals_id, :sals_attributes

before_save :set_default_value
  def set_default_value
            self.wday = 26 
  end

before_save :calculate_day
  def calculate_day
      self.attend_day = self.wday-self.el-self.cl-self.sl
  end
end

app/models/deduct.rb
class Deduct < ActiveRecord::Base
belongs_to :employee
has_many :sals

  attr_accessible :esi, :pf, :share, :te, :employee_id, :deducts_id, :deducts_attributes, :total_deduction

before_save :calculate_value
def calculate_value
   self.total_deduction = self.pf+self.esi+self.share+self.te
end

end

app/models/employee.rb
class Employee < ActiveRecord::Base

has_many :sals
accepts_nested_attributes_for :sals

has_many :deducts
accepts_nested_attributes_for :deducts

has_many :attendances
accepts_nested_attributes_for :attendances

 attr_accessible :address, :dob, :emp_branch, :emp_category, :emp_code, :emp_designation, :emp_name, :end_date, :start_date, :Age, :gender, :address, :mobile, :sals_id, :deducts_id,  :attendances_id
attr_accessible :deducts_attributes, :sals_attributes, :attendances_attributes


before_create :increment_code
def increment_code
    self.emp_code = (self.class.last.nil?) ? "00001" : ((self.class.last.emp_code.to_i) + 1).to_s.rjust(5,'0')
end

end

app/models/sal.rb
class Sal < ActiveRecord::Base
belongs_to :employee
belongs_to :attendance
belongs_to :deduct

register_currency :inr

monetize :basic_paisa, :cca_paisa, :da_paisa, :exp_paisa, :hra_paisa, :spl_paisa, :total_paisa, :net_sal_paisa, :gross_paisa
 
attr_accessible :basic_currency, :cca_currency, :da_currency, :exp_currency, :hra_currency, :spl_currency, :total_currency, :basic_paisa, :cca_paisa, :da_paisa, :exp_paisa, :hra_paisa, :spl_paisa, :total_paisa, :employee_id, :gross_currency, :net_sal_currency
attr_accessor :lop, :total_deduction
attr_accessible :lop, :total_deduction

before_save :calculate_total 
  def calculate_total
    self.total_paisa = self.basic_paisa+self.da_paisa+self.hra_paisa+self.cca_paisa+self.spl_paisa+self.exp_paisa
  end

  before_save :calculate_gross
  def calculate_gross
  	self.gross_paisa = self.total_paisa-attendance.lop
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

 def new
  @attendance = Attendance.new
  @attendance.employee_id = params[:id]
 end

 def create
  @attendance = Attendance.new(params[:attendance]) 
   if @attendance.save
   redirect_to attendances_path(@attendance)
   else
    render new
   end
 end 

 def edit
 @attendance = Attendance.find(params[:id])
 end

 def index
  @attendances = Attendance.all
 end 


 def update
  @attendance = Attendance.find(params[:id])
   if @attendance.update_attributes(params[:attendance])
    flash[:success] = "updated successfully"
    redirect_to employee_path(@attendance)
    else
    flash[:alert] = "failed"
    render 'edit'
   end
 end

end

app/controllers/deducts_controller.rb
class DeductsController < ApplicationController
 def new
  @deduct = Deduct.new
  @deduct.employee_id = params[:id]
 end

 def create
  @deduct = Deduct.new(params[:deduct])
   if @deduct.save
     redirect_to  employees_path(@deduct)
   else
     render "new"
   end 
 end

 def edit
  @deduct = Deduct.find(params[:id])
 end

 def update
  @deduct = Deduct.find(params[:id])
   if @deduct.update_attributes(params[:deduct])
    flash[:success] = "updated successfully"
    redirect_to employee_path(@deduct)
    else
    flash[:alert] = "failed"
    render 'edit'
   end
 end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

 def new
  @employee = Employee.new
  @sal = @employee.sals.build
  @deduct = @employee.deducts.build
  @attendance = @employee.attendances.build
 end

 def create
  @employee = Employee.new(params[:employee])
   if @employee.save
     flash[:success] = "Welcome"
     redirect_to  employees_path(@employee)
   else
     flash[:alert] = "employee not added"
     render "new"
   end 
 end

 def index
  @employees = Employee.all
  @employees = Employee.where("emp_code LIKE ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 15)

 end 

 def show
  @employee = Employee.find(params[:id])
 end
 
 def edit
  @employee = Employee.find(params[:id])
 end

 def update
  @employee = Employee.find(params[:id])
   if @employee.update_attributes(params[:employee])
    flash[:success] = "updated successfully"
    redirect_to employees_path(@employee)
    else
    flash[:alert] = "failed"
    render 'edit'
   end
 end

 def destroy
  @employee = Employee.find(params[:id])
  @employee.destroy
  flash[:notice] = "employee has been deleted"
  redirect_to employees_path
 end
end

app/controllers/sals_controller.rb
class SalsController < ApplicationController

 def new
  @sal = Sal.new

  @sal.employee_id = params[:id]

 end

 def create
  @sal = Sal.new(params[:sal])
   if @sal.save
    redirect_to employees_path(@sal)
   else
    render "new"
   end 
 end

 def index
  @sals = Sal.all
 end 

 def edit
  @sal = Sal.find(params[:id])
 end

 def update
   @sal = Sal.find(params[:id])
    if @sal.update_attributes(params[:sal])
      redirect_to employee_path(@sal)
    else
      render 'edit'
    end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/deducts_helper.rb
module DeductsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sals_helper.rb
module SalsHelper
end

app/views/attendances/edit.html.erb
<h1>Add Employee Attendance Details</h1>
 <%= form_for @attendance  do |b| %>


<h4><%= b.label :number_of_working_days %></h4>
<h4><%= b.text_field :wday, :value => 26, :readonly => true %></h4>


<h4><%= b.label :casual_leave, class:'required' %></h4>
<h4><%= b.text_field :cl %></h4>


<h4><%= b.label :sick_leave, class:'required' %></h4>
<h4><%= b.text_field :sl %></h4>


<h4><%= b.label :earned_leave, class:'required' %></h4>
<h4><%= b.text_field :el %></h4>


<h4><%= b.label :on_duty, class:'required' %></h4>
<h4><%= b.text_field :od %></h4>

<h4><%= b.label :loss_of_pay, class:'required' %></h4>
<h4><%= b.text_field :lop %></h4>
<fieldset class="form-actions"> <%= b.submit "UPDATE", class: "btn btn-primary" %></field>
<% end %>
<br /><br /><br />

app/views/attendances/index.html.erb
<h1>LIST OF EMPLOYEE ATTENDANCE DETAILS</h1>


<div><table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table"><br />
  <tr>
    <th>Employee ID</th>
    <th>Employee name</th>
    <th>number of working days</th>
    <th>casual leave</th>
    <th>sick leave</th>
    <th>earned leave</th>
    <th>on duty</th>
    <th>loss of pay</th>
  </tr>


   <tr>
   <td><% for sal in @employee.sals %><%= sal.basic_paisa %><% end %></td>
   <td><% for sal in @employee.sals %><%= sal.basic_paisa %><% end %></td>
  <% @attendances.each do |attendance| %>
    <td><%= attendance.wday %></td>
    <td><%= attendance.cl %></td>
    <td><%= attendance.sl %></td>
    <td><%= attendance.el %></td>
    <td><%= attendance.od %></td>
    <td><%= attendance.lop %></td>
   </tr>
  <% end %>
 </table>
</div>

app/views/attendances/new.html.erb
<h1>Employee Attendance detail</h1>
<%= form_for @attendance do |f| %>

<%= f.hidden_field :employee_id, :value => params[:id] %>

<br />
<h4><%= f.label :number_of_working_days %></h4>
<h4><%= f.text_field :wday, :value => 26, :readonly => true %></h4>

<h4><%= f.label :casual_leave, class:'required' %></h4>
<h4><%= f.text_field :cl %></h4>


<h4><%= f.label :sick_leave, class:'required' %></h4>
<h4><%= f.text_field :sl %></h4>


<h4><%= f.label :earned_leave, class:'required' %></h4>
<h4><%= f.text_field :el %></h4>


<h4><%= f.label :on_duty, class:'required' %></h4>
<h4><%= f.text_field :od %></h4>

<h4><%= f.label :loss_of_pay, class:'required' %></h4>
<h4><%= f.text_field :lop %></h4>


<fieldset class="form-actions"> <%= f.submit "Create", class: "btn btn-primary" %></field>

<% end %>

app/views/deducts/edit.html.erb
<h1>EDIT ALLOWANCE DETAILS</h1>

<%= form_for @deduct do |f| %>

<h4><%= f.label :pf, class:'required' %></h4>
<h4><%= f.text_field :pf %></h4>

<h4><%= f.label :esi, class:'required' %></h4>
<h4><%= f.text_field :esi %></h4>

<h4><%= f.label :te, class:'required' %></h4>
<h4><%= f.text_field :te %></h4>

<h4><%= f.label :share, class:'required' %></h4>
<h4><%= f.text_field :share %></h4>


<fieldset class="form-actions"> <%= f.submit "UPDATE", class: "btn btn-primary" %></field>
<% end %>

app/views/deducts/new.html.erb
<h1>Allowance DETAILS</h1>

<%= form_for @deduct do |f| %>
<%= f.hidden_field :employee_id, :value => params[:id] %>
<h4><%= f.label :pf, class:'required' %></h4>
<h4><%= f.text_field :pf %></h4>

<h4><%= f.label :esi, class:'required' %></h4>
<h4><%= f.text_field :esi %></h4>

<h4><%= f.label :te, class:'required' %></h4>
<h4><%= f.text_field :te %></h4>

<h4><%= f.label :share, class:'required' %></h4>
<h4><%= f.text_field :share %></h4>


<fieldset class="form-actions"> <%= f.submit "Create", class: "btn btn-primary" %></field>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit Employee details</h1>
<em><h5>NOTE: Fill all the text boxes and click Update button</h5></em>
<%= form_for @employee do |f| %>

 <div class='span6'>
   <h4><%= f.label :Name, class:'required' %></h4>
   <h4><%= f.text_field :emp_name, :placeholder => "employee name" %></h4>
 </div>

   <h4><%= f.label :Category, class:'required' %>
   <%= f.select :emp_category, options_for_select([["Contractual", "contractual"], ["Permanant",  "permanant"], ["Trainee","trainee"]]), { :include_blank => true } %></h4>

 <div class='span6'>
   <h4><%= f.label :Age %></h4>
<h4><%= f.text_field :Age, :placeholder => "employee age" %></h4>
</div><br />

<h4><%= f.label :Branch, class:'required' %></h4>
<h4><%= f.text_field :emp_branch, :placeholder => "employee branch" %></h4>

<div class='span6'>
<h4><%= f.label :Address %></h4>
<h4><%= f.text_area :address, :placeholder => "fill the address", :rows => 3, :cols => 3 %></h4>
</div><br />

<h4><%= f.label :Designation, class:'required' %></h4>
<%= f.select :emp_designation, options_for_select([["AAO", "aao"], ["AO", "ao"], ["APPRAISER", "appariser"], ["ASSISTANT MANAGER", "assistant manager"], ["CLERK", "clerk"], ["CHEIF MANAGER", "cheif manager"], ["J-CLERK", "jclerk"], ["MANAGER", "manager"], ["SUB-STAFF", "sub-staff"]]), { :include_blank => true } %>

<script>
  $(function() {
    $( "#datepicker1" ).datepicker();
    $( "#datepicker2" ).datepicker();
    $( "#datepicker3" ).datepicker();
  });
  </script>
<div class='span6'>
<h4><%= f.label :DOB, class:'required' %></h4>
<h4><%= f.text_field :dob, :id => "datepicker1", :placeholder => "date of birth" %></h4>
</div><br />


<h4><%= f.label :Start_date, class:'required' %></h4>
<h4><%= f.text_field :start_date, :id => "datepicker2", :placeholder => "start date" %></h4>

<div class='span6'>
<h4><%= f.label :Gender %></h4>
 <%= f.select :gender, options_for_select([["Female", "female"], ["Male", "male"]]), { :include_blank => true } %>
</div><br />

<h4><%= f.label :End_date %></h4>
<h4><%= f.text_field :end_date, :id => "datepicker3", :placeholder => "end date" %></h4>

<div class='span6'>
<h4><%= f.label :Mobile, class:'required' %></h4>
<h4><%= f.text_field :mobile, :placeholder => "mobile" %></h4>
</div><br /><br /><br /><br />

<fieldset class="form-actions"> <%= f.submit "Update", class: "btn btn-primary" %></field>
<% end %>
<%= link_to "BACK", employee_path(@employee), class: "btn" %>

app/views/employees/index.html.erb
<h1>LIST OF EMPLOYEE</h1>

<div class='span6 offset6'>
   <%= form_tag employees_path, :method => 'get', :class => "form-search" do %>
   <%= text_field_tag :search, nil, :placeholder => "Enter the code", 
      :class => "input-medium search-query" %>
   <%= submit_tag "search!", :name => nil, :class => "btn" %><br /><br />
   <% end %>
</div><br /><br />


<h6 class= "alert alert-info"><%= page_entries_info @customers %></h6>
<div><table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table">
  <tr>
    <th>EMP CODE</th>
    <th>EMP NAME</th>
    <th>CATEGORY</th>
    <th>DESIGNATION</th>
    <th>BRANCH</th>
    <th>ATTENDANCE DETAILS</th>
    <th>DEDUCTION DETAILS</th>
    <th>EMP SALARY DETAILS</th>
    <th>DELETE</th>
  </tr>

  <% @employees.each do |employee| %>
   <tr>
    <td><%= employee.emp_code %></td>
    <td><%= link_to "#{employee.emp_name}", employee_path(employee) %></td>
    <td><%= employee.emp_category %></td>
    <td><%= employee.emp_designation %></td>
    <td><%= employee.emp_branch %></td>
    <td><%= link_to "Add details",new_attendance_path(:id=>employee.id),class: "btn-primary btn" %></td>
    <td><%= link_to "Add details", new_deduct_path(:id=>employee.id),class: "btn-primary btn" %></td>
    <td><%= link_to "Add details", new_sal_path(:id=>employee.id),class: "btn-primary btn" %></td>
    <td><%= link_to "Delete",employee_path(employee),class: "btn btn-danger",
      method: :delete, confirm: "Are You Sure?" %></td>
   </tr>
  <% end %>
 </table>


<%= will_paginate @employees %>
</div>
<%= link_to "Add New Employee", new_employee_path,class: "btn" %>

app/views/employees/new.html.erb
<h1>Employee detail</h1>
<%= form_for @employee do |f| %>

<div class='span6'>
<h4><%= f.label :Name, class:'required' %></h4>
<h4><%= f.text_field :emp_name, :placeholder => "employee name" %></h4>
</div>

<h4><%= f.label :Category, class:'required' %>
<%= f.select :emp_category, options_for_select([["Contractual", "contractual"], ["Permanant",  "permanant"], ["Trainee","trainee"]]), { :include_blank => true } %>
 </h4>

<div class='span6'>
<h4><%= f.label :Age %></h4>
<h4><%= f.text_field :Age, :placeholder => "employee age" %></h4>
</div><br />

<h4><%= f.label :Branch, class:'required' %></h4>
<h4><%= f.text_field :emp_branch, :placeholder => "employee branch" %></h4>

<div class='span6'>
<h4><%= f.label :Address %></h4>
<h4><%= f.text_area :address, :placeholder => "fill the address", :rows => 3, :cols => 3 %></h4>
</div><br />

<h4><%= f.label :Designation, class:'required' %></h4>
<%= f.select :emp_designation, options_for_select([["AAO", "aao"], ["AO", "ao"], ["APPRAISER", "appariser"], ["ASSISTANT MANAGER", "assistant manager"], ["CLERK", "clerk"], ["CHEIF MANAGER", "cheif manager"], ["J-CLERK", "jclerk"], ["MANAGER", "manager"], ["SUB-STAFF", "sub-staff"]]), { :include_blank => true } %>

<script>
  $(function() {
    $( "#datepicker1" ).datepicker({format: 'yyyy-mm-dd'});
    $( "#datepicker2" ).datepicker({format: 'yyyy-mm-dd'});
    $( "#datepicker3" ).datepicker({format: 'yyyy-mm-dd'});
  });
  </script>
<div class='span6'>
<h4><%= f.label :DOB, class:'required' %></h4>
<h4><%= f.text_field :dob, :id => "datepicker1", :placeholder => "date of birth" %></h4>
</div><br />


<h4><%= f.label :Start_date, class:'required' %></h4>
<h4><%= f.text_field :start_date, :id => "datepicker2", :placeholder => "start date" %></h4>

<div class='span6'>
<h4><%= f.label :Gender %></h4>
 <%= f.select :gender, options_for_select([["Female", "female"], ["Male", "male"]]), { :include_blank => true } %>
</div><br />

<h4><%= f.label :End_date %></h4>
<h4><%= f.text_field :end_date, :id => "datepicker3", :placeholder => "end date" %></h4>

<div class='span6'>
<h4><%= f.label :Mobile, class:'required' %></h4>
<h4><%= f.text_field :mobile, :placeholder => "mobile" %></h4>
</div><br />

<fieldset class="form-actions"> <%= f.submit "Create", class: "btn btn-primary" %></field>
<% end %>

app/views/employees/show.html.erb
<h1>Employee Details</h1><br />
 <div class='span6 offset6'>
  <%= link_to "Edit Employee Details",edit_employee_path(@employee),class: "btn-primary btn" %>
  <%= link_to "Delete Employee",employee_path(@employee),class: "btn btn-danger",
      method: :delete, confirm: "Are You Sure?" %>
  <%= link_to "BACK", employees_path,class: "btn-primary btn" %>
 </div><br />

<h5><STRONG>NAME         :</STRONG> <%= @employee.emp_name %></h5>
<h5><STRONG>EMPLOYEE CODE:</STRONG> <%= @employee.emp_code %></h5>
<h5><STRONG>CATEGORY     :</STRONG> <%= @employee.emp_category %></h5>
<h5><STRONG>DESIGNATION  :</STRONG> <%= @employee.emp_designation %></h5>
<h5><STRONG>BRANCH       :</STRONG> <%= @employee.emp_branch %></h5>
<h5><STRONG>JOINING DATE :</STRONG> <%= @employee.start_date %></h5>
<h5><STRONG>END DATE     :</STRONG> <%= @employee.end_date %></h5><br />

<h1>Attendance details</h1>
 <div class='span6 offset6'>
 <%= link_to "Edit",edit_attendance_path, class: "btn-primary btn" %>
 </div><br />

<h5>WORKING DAY  :<% for attendance in @employee.attendances %><%= attendance.wday %><% end %></h5>
<h5>ATTEND DAY   :<% for attendance in @employee.attendances %><%= attendance.attend_day %><% end %></h5>
<h5>ON-DUTY      :<% for attendance in @employee.attendances %><%= attendance.od %><% end %></h5>
<h5>EARNED LEAVE :<% for attendance in @employee.attendances %><%= attendance.el %><% end %></h5>
<h5>CASUAL LEAVE :<% for attendance in @employee.attendances %><%= attendance.cl %><% end %></h5>
<h5>SPECIAL LEAVE:<% for attendance in @employee.attendances %><%= attendance.sl %><% end %></h5>
<h5>LOSS OF PAY  :<% for attendance in @employee.attendances %><%= attendance.lop %><% end %></h5>

<br /><h1>Salary details</h1>
 <div class='span6 offset6'>
 <%= link_to "Edit",edit_sal_path, class: "btn-primary btn" %>
 </div><br />

<h5>BASIC PAY          :<% for sal in @employee.sals %><%= sal.basic_paisa %><% end %></h5>
<h5>DA                 :<% for sal in @employee.sals %><%= sal.da_paisa %><% end %></h5>
<h5>HRA                :<% for sal in @employee.sals %><%= sal.hra_paisa %><% end %></h5>
<h5>CCA                :<% for sal in @employee.sals %><%= sal.cca_paisa %><% end %></h5>
<h5>SPL                :<% for sal in @employee.sals %><%= sal.spl_paisa %><% end %></h5>
<h5>EXP                :<% for sal in @employee.sals %><%= sal.exp_paisa %><% end %></h5>
<h5>TOTAL              :<% for sal in @employee.sals %><%= sal.total_paisa %><% end %></h5>
<h5>GROSS              :<% for sal in @employee.sals %><%= sal.gross_paisa  %><% end %></h5>
<h5>NET SALARY         :<% for sal in @employee.sals %><%= sal.net_sal_paisa %><% end %></h5>


<br /><h1>Deduction details</h1>
 <div class='span6 offset6'>
 <%= link_to "Edit",edit_deduct_path, class: "btn-primary btn" %>
 </div><br />

<h5>PF                :<% for deduct in @employee.deducts %><%= deduct.pf %><% end %></h5>
<h5>ESI               :<% for deduct in @employee.deducts %><%= deduct.esi %><% end %></h5>
<h5>TE                :<% for deduct in @employee.deducts %><%= deduct.te %><% end %></h5>
<h5>SHARE             :<% for deduct in @employee.deducts %><%= deduct.share %><% end %></h5>

<br /><%= link_to "Back",employees_path(@employee),class: "btn-primary btn" %>
<br /><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
<meta http-equiv="Content-Type" content="text/html; chaarset=utf-8"/>
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>

<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

<%= csrf_meta_tags %>
<title>Payroll</title>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sals/edit.html.erb
<h1> EDIT SALARY DETAILS</h1>
<%= form_for @sal do |f| %>

<h4><%= f.label :basic, class:'required' %></h4>
<h4><%= f.text_field :basic_paisa %></h4>

<h4><%= f.label :da, class:'required' %></h4>
<h4><%= f.text_field :da_paisa %></h4>

<h4><%= f.label :hra, class:'required' %></h4>
<h4><%= f.text_field :hra_paisa %></h4>

<h4><%= f.label :cca, class:'required' %></h4>
<h4><%= f.text_field :cca_paisa %></h4>

<h4><%= f.label :spl, class:'required' %></h4>
<h4><%= f.text_field :spl_paisa %></h4>

<h4><%= f.label :exp, class:'required' %></h4>
<h4><%= f.text_field :exp_paisa %></h4>

<fieldset class="form-actions"> <%= f.submit "UPDATE", class: "btn btn-primary" %></field>
<% end %>

app/views/sals/new.html.erb
<h1>SALARY DETAILS</h1>
<%= form_for @sal do |f| %>
<%= f.hidden_field :employee_id, :value => params[:id] %>
<h4><%= f.label :basic, class:'required' %></h4>
<h4><%= f.text_field :basic_paisa %></h4>

<h4><%= f.label :da, class:'required' %></h4>
<h4><%= f.text_field :da_paisa %></h4>

<h4><%= f.label :hra, class:'required' %></h4>
<h4><%= f.text_field :hra_paisa %></h4>

<h4><%= f.label :cca, class:'required' %></h4>
<h4><%= f.text_field :cca_paisa %></h4>

<h4><%= f.label :spl, class:'required' %></h4>
<h4><%= f.text_field :spl_paisa %></h4>

<h4><%= f.label :exp, class:'required' %></h4>
<h4><%= f.text_field :exp_paisa %></h4>

<fieldset class="form-actions"> <%= f.submit "Create", class: "btn btn-primary" %></field>
<% end %>